CREATE DATABASE dbshipping;
GRANT ALL PRIVILEGES ON DATABASE dbshipping TO dbuser;
CREATE DATABASE dbinvoicing;
GRANT ALL PRIVILEGES ON DATABASE dbinvoicing TO dbuser;
CREATE DATABASE dborder;
GRANT ALL PRIVILEGES ON DATABASE dborder TO dbuser;