version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    links:
     - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "order:5:1"
  apache:
    image: hakobhn/microservice-order-apache:1.0.0
    links:
     - order
     - shipping
     - invoicing
    ports:
     - "8080:80"
  postgres:
    image: hakobhn/microservice-order-postgres:1.0.0
    restart: always
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
    ports:
      - '5434:5432'
    volumes:
      - ../../.data/db/postgres-docker:/var/lib/postgresql/data
  order:
    image: hakobhn/microservice-order-ordering:1.0.0
    restart: always
    links:
     - kafka
     - postgres
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  shipping:
    image: hakobhn/microservice-order-shipping:1.0.0
    restart: always
    links:
     - kafka
     - postgres
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  invoicing:
    image: hakobhn/microservice-order-invoicing:1.0.0
    restart: always
    links:
     - kafka
     - postgres
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

volumes:
  postgres:
    driver: local