apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: ordering
  labels:
    name: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: node
          image: hakobhn/microservice-order-ordering:1.0.0
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: ordering
  labels:
    service: order
spec:
  ports:
    - nodePort: 30180
      port: 8080
      targetPort: 8080
  type: LoadBalancer
  selector:
    app: order