apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: ordering
spec:
  replicas: 1
  selector:
    matchLabels:
      service: postgres
  template:
    metadata:
      labels:
        service: postgres
    spec:
      containers:
        - name: postgres
          image: hakobhn/microservice-order-postgres:1.0.0
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
              name: pg-port
              protocol: TCP
          volumeMounts:
            - name: postgredb
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
      restartPolicy: Always
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: ordering
  labels:
    service: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      name: pg-port
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres