apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: ordering
  labels:
    type: local
    name: postgres
spec:
  capacity:
    storage: 5Gi
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "C:\\Users\\Hakob_Hakobyan3\\IdeaProjects\\microservices-order\\.data\\db\\postgres-k8s"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  namespace: ordering
  labels:
    app: postgres
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi