apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    type: local
    name: postgres-pv
spec:
  capacity:
    storage: 5Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "C:\\Users\\Hakob_Hakobyan3\\IdeaProjects\\microservices-order\\.data\\db\\postgres-k8s"