kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka
  namespace: ordering
spec:
  replicas: 1
  selector:
    matchLabels:
      service: zookeeper
  template:
    metadata:
      labels:
        service: zookeeper
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka:2.12-2.5.0
        ports:
          - containerPort: 9092
        env:
          - name: ENABLE_AUTO_EXTEND
            value: "true"
          - name: ENABLE_CLIENT_SASL_KEY
            value: "false"
          - name: KAFKA_RESERVED_BROKER_MAX_ID
            value: "999999999"
          - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
            value: "true"
          - name: KAFKA_PORT
            value: "9092"
          - name: KAFKA_ADVERTISED_PORT
            value: "9092"
          - name: KAFKA_ADVERTISED_HOST_NAME
            value: "kafka"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zookeeper:2181
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: ordering
  labels:
    service: kafka
spec:
  type: ClusterIP
  ports:
    - port: 9092
      name: kafka-port
      targetPort: 9092
      protocol: TCP
  selector:
    app: kafka