apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoicing
  namespace: ordering
  labels:
    name: invoicing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invoicing
  template:
    metadata:
      labels:
        app: invoicing
    spec:
      containers:
        - name: invoicing-node
          image: hakobhn/microservice-order-invoicing:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: invoicing
  namespace: ordering
  labels:
    service: invoicing
spec:
  selector:
    app: invoicing
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080